services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE${DB_USER:***REMOVED***}docker
    depends_on:
      - redis
    networks:
      - domain-registrar-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - domain-registrar-network
    command: redis-server --appendonly yes

  domain-order-service:
    build:
      context: .
      dockerfile: domain-order-service/Dockerfile
    container_name: domain-order-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE${DB_USER:***REMOVED***}docker
    depends_on:
      - ***REMOVED***-domain-order
    networks:
      - domain-registrar-network

  ***REMOVED***-domain-order:
    image: ***REMOVED***:15-alpine
    container_name: ***REMOVED***-domain-order
    environment:
      POSTGRES_DB: domain_order_db
      POSTGRES_USER: ***REMOVED***
      POSTGRES_PASSWORD: ***REMOVED***
    ports:
      - "5432:5432"
    volumes:
      - ***REMOVED***-domain-order-data:/var/lib/***REMOVED***ql/data
    networks:
      - domain-registrar-network

volumes:
  redis-data:
  ***REMOVED***-domain-order-data:

networks:
  domain-registrar-network:
    driver: bridge
